{
  "contest": 304,
  "handle": "0xbrett8571",
  "risk": "2",
  "title": "ZRC20's withdraw() external call allows reentrancy, risking unintended consequences in state.",
  "issueId": 40,
  "issueUrl": "https://github.com/code-423n4/2023-11-zetachain-findings/issues/40"
}