{
  "contest": 304,
  "handle": "0xOmer",
  "risk": "3",
  "title": "Missing function call causes loss of user's ETH",
  "issueId": 368,
  "issueUrl": "https://github.com/code-423n4/2023-11-zetachain-findings/issues/368"
}