{
  "contest": 304,
  "handle": "p0wd3r",
  "risk": "2",
  "title": "In some cases, calling on `nil` occurs, which then triggers a panic.",
  "issueId": 194,
  "issueUrl": "https://github.com/code-423n4/2023-11-zetachain-findings/issues/194"
}